### ISSUE TITLE
[Game] Mega Man Zero 4 slow downs during "Mission Start" logo and underground vehicle animation in DS mode

### ISSUE THREAD

**Issue by Dartz150** [Gericom/GBARunner3#27]
Video on the Discord Server GBARunner3 channel:

https://discord.com/channels/283769550611152897/620310871800807466/1156985213767921764

**Comment by Gericom** [comment]
This is related to hblank irqs being triggered, even on scanlines that do not exist on the gba, and also to jit performance overhead

**Comment by Gericom** [comment]
Mega Man Zero 2 works now with jit detached in the jit detach branch, but has strange graphical glitches after the mission start text disappears. They can be resolved by opening and closing the pause menu.

**Comment by Gericom** [comment]
Graphical issue is solved now as well

**Comment by Dartz150** [comment]
DS mode is still having some performance issues during these animations, DSi mode runs almost ok, but still has some flickering.

The weird bug on Mega Man Zero 4 where some lines at the bottom of the logos were stuck has been fixed.

**Comment by Dartz150** [comment]
The issue is gone as of commit [2f0609f](https://github.com/Gericom/GBARunner3/commit/2f0609f7d3885cf8f5af3a9938f2b53d3e08982d) on every title except MMZ4, where it causes major overhead in regular DS mode, DSi mode runs as expeccted.
